### ISSUE TITLE
Got error when deploy to kintone

### ISSUE THREAD

**Issue by bocanhcam** [kintone-labs/kintone-cli#204]
```sh
kintone-cli deploy --app-name test-template2
```
Start uploading customization files
test-template2/dist/test-template2.min.js has been uploaded!
test-template2/dist/test-template2.min.js has been uploaded!
JavaScript/CSS files have been uploaded!
Failed to update customize setting
An error occurred, retry
Failed to update customize setting
An error occurred, retry
Failed to update customize setting
KintoneRestAPIError: [400] [CB_VA01] Missing or invalid input. (p6OtnYa9uopRUUfb7Bq4)
    at KintoneResponseHandler.handleErrorResponse (/home/hoangdv/Documents/test-kintone/node_modules/@kintone/rest-api-client/lib/src/KintoneResponseHandler.js:57:15)
    at /home/hoangdv/Documents/test-kintone/node_modules/@kintone/rest-api-client/lib/src/KintoneResponseHandler.js:35:123
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by TomokoMiyake** [comment]
@bocanhcam 
Sorry to be late to respond.
We will check it, so please wait for a while.

**Comment by TomokoMiyake** [comment]
@bocanhcam 
I tried with the latest version of kintone-cli v0.5.1 and succeeded in uploading customization file to the kintone domain.
Could you please confirm whether you use the latest version?
